name: 'Kubernetes Manifests Diff'
description: 'Compare Kubernetes manifests between PR branch and target branch'
author: 'Jonas Olander'

inputs:
  current_manifests_path:
    description:
      'Path to the file containing manifests from the current PR branch'
    required: true
  target_manifests_path:
    description: 'Path to the file containing manifests from the target branch'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
