name: 'Kubernetes Manifests Diff'
description: 'Compare Kubernetes manifests between PR branch and target branch'
author: 'Jonas Olander'

inputs:
  current_manifests_path:
    description:
      'Path to the file containing manifests from the current PR branch'
    required: true
  target_manifests_path:
    description: 'Path to the file containing manifests from the target branch'
    required: true
  github_token:
    description: 'GitHub token for posting comments'
    required: false
    default: ${{ github.token }}
  title:
    description:
      'Custom title for the diff comment (default: "Kubernetes Manifests Diff")'
    required: false
    default: 'Kubernetes Manifests Diff'
  subtitle:
    description:
      'Optional subtitle to add below the title for additional context'
    required: false
    default: ''
  max_comment_char_len:
    description:
      'Maximum length of a single comment. If exceeded, the comment will be
      split.'
    required: false
    default: '600000'

runs:
  using: 'node20'
  main: 'dist/index.js'
